// Generated by CoffeeScript 1.4.0
(function() {
  var Config, Logger, WebServer, express, http,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  express = require('express');

  http = require('http');

  require('pkginfo')(module, 'name', 'version');

  Config = require('./config');

  Logger = require('./logger');

  /**
   * The webserver class.
  */


  WebServer = (function() {

    function WebServer() {
      this.setup_routing = __bind(this.setup_routing, this);
      this.config = Config.get();
      this.logger = Logger.get();
      this.app = express();
      this.app.use(express.bodyParser());
      this.app.use(this.errorHandler);
      this.setup_routing();
      this.srv = http.createServer(this.app);
      this.srv.listen(this.config.get('port'));
      this.logger.info("Webserver is up at: http://0.0.0.0:" + (this.config.get('port')));
    }

    WebServer.prototype.errorHandler = function(err, req, res, next) {
      res.status(500);
      return res.render('error', {
        error: err
      });
    };

    WebServer.prototype.setup_routing = function() {
      var _this = this;
      this.app.get('/', function(req, res, next) {
        return res.json(200, {
          name: exports.name,
          version: exports.version
        });
      });
      return this.app.get('/favicon.ico', function(req, res, next) {
        return res.json(404, "No favicon exists.");
      });
    };

    return WebServer;

  })();

  module.exports = WebServer;

}).call(this);
